
/*
Mills, S.G. and Rothwell, J.D. 1982: Predicting diseases - the hygrothermograph. Greenmaster, 18(4), 14-15.
*/


export default class TurfTextStore {
  app;
  constructor(app) {
    this.app = app;

    this.descriptions = {

      anthrac:['<h3>About Anthracnose Disease Risk</h3>',
               '<p>The Anthracnose risk index is based on the model of <i>Danneberger',
               'et al. (1984)</i> (see references below) with slight modifications for compatibility',
               'with available gridded weather observations. The model combines leaf wetness (Lw)',
               'and air temperature (T) into a single index (Ia) that is used to estimate the risk of',
               'an outbreak. The equation describing the index is :',
               '</p>',
               '<p>&nbsp;&nbsp;&nbsp;&nbsp;<i>Ia = 4.0233 - 0.2283(Lw) - 0.5303(T) - 0.0013(Lw<sup>2</sup>) + 0.0197(T<sup>2</sup>) + 0.0155(T × Lw)</i>',
               '<p/>',
               '<p>Lw is the average number of hours per day that leaf wetness was present during the',
               'previous three days. Any hourly weather observation that reports either rainfall or a',
               'dew point that is less than three degrees (°C) lower than the air temperature indicates',
               'leaf wetness, indicates the occurrence  leaf wetness during that hour and the next hour.',
               'T is the average air temperature (°C) for the previous three days.',
               '</p>',
               '<p>On a daily basis, <span class="high">high risk</span> is indicated when the index exceeds 1.5. <span class="moderate">Moderate risk</span>',
               'corresponds to index values between 0.4 and 1.5. <span class="no_risk">Low risk</span> is assumed for index values',
               'of  0.4 or less. In general higher index values occur with higher temperatures and more',
               'prolonged leaf wetness.',
               '<p/>',
               'The weekly index values reflect the longer-term persistence of Anthracnose risk. They',
               'are simply a 7-day average of the daily index values. High, Moderate and low risk are',
               'based on the same index thresholds, but using 7-day averages rather than daily values.',
               'In general, <span class="high">high weekly risk</span> indicates consistent (4 or more days) of moderate',
               'to high daily risk, <span class="moderate">moderate weekly risk</span> indicates 2 or 3 days of moderate',
               'to high daily risk and <span class="no_risk">low weekly risk</span> indicates 2 or fewer days of moderate risk.',
               '<p/>',
               '<p>The weather data used to compute the Anthracnose index is from the National Weather',
               'Service’s <a href="http://www.nco.ncep.noaa.gov/pmb/products/rtma"> Real-time Mesoscale Analysis (RTMA)</a>. Forecasted risk uses data from the',
               '<a href="https://www.weather.gov/mdl/ndfd_home"> National Digital Forecast Database (NDFD)</a>.',
               '</p>',
               '<h3>References</h3>',
               '<p>Danneberger, T.K., J.M. Vargas Jr., and A.L. Jones, 1984:',
               '<i>A model for weather-based forecasting of anthracnose on annual bluegrass.</i>',
               'Phytopathology, 74, 448-451',
               '</p>'
              ].join(' '),

      bpatch:['<h3>About Brown Patch Disease Risk</h3>',
              '<p>The Brown Patch risk index is based on the model of <i>Fidanza et al. (1996)</i> (see reference below)',
              'with slight modifications for compatibility with available gridded weather observations.',
              'The model uses a combines relative humidity (RH), leaf wetness (Lw) and daily minimum',
              'air temperature (Tmin) into a single index (Ibp) the is used to estimate the risk of an',
              'outbreak. The equation describing the index is :',
              '</p>',
              '<p>&nbsp;&nbsp;&nbsp;&nbsp;<i>Ibp = RH<sub>80</sub> + RH<sub>95</sub> + Lw + Tmin</i><br/>',
              '</p>',
              '<p>RH<sub>80</sub> equals 1 when the daily average relative humidity is 80 or above, otherwise it is set',
              'to 0. RH<sub>95</sub> is assigned a value 1 if more than 4 hourly RH values in a day',
              'exceed 95 and a value of 2 if 8 or more hours exceed 95, otherwise it is set to zero.',
              'Lw is set to 1 when leaf wetness is present during 10 or more hours in a day, otherwise',
              'it is assigned a value of 0. Any hourly weather observation that reports either rainfall',
              'or a dew point that is less than three degrees (°C) lower than the air temperature',
              'indicates that leaf wetness occurred during that hour and the next hour.',
              '</p>',
              '<p>From July 1 to September 30 Tmin is assigned a value of -2. Prior to July 1 and after',
              'September 30, the value of Tmin is -4. Regardless of date, on days when the minimum',
              'temperature is 16°C (60.8°F) or higher Tmin is assigned a value of 1.', 
              '</p>',
              '<p>On a daily basis, <span class="high">high risk</span> is indicated when the average of the index over the',
              'previous 3 days exceeds 0.9. <span class="moderate">Moderate risk</span> corresponds to 3-day average index values',
              'between 0.4 and 0.9. <span class="no_risk">Low risk</span> is assumed for 3-day average index values of 0.4 or less.',
              'In general higher index values occur with higher temperatures, more prolonged leaf wetness',
              'and higher relative humidity.',
              '</p>',
              '<p>The weekly index values reflect the longer-term persistence of brown patch risk.',
              'They are simply a 7-day average of the daily index values. High, Moderate and low risk',
              'are based on the same index thresholds, but using the 7-day averages rather than daily values.',
              'In general, <span class="high">high weekly risk</span> indicates consistent (4 or more days) of moderate to high daily risk',
              '<span class="moderate">moderate weekly risk</span> indicates 2 or 3 days of moderate to high daily risk and <span class="no_risk">low weekly risk</span>',
              'indicates 2 or fewer days with moderate risk.',
              '</p>',
              '<p>The weather data used to compute the Brown Patch index is from the National Weather',
              'Service’s <a href="http://www.nco.ncep.noaa.gov/pmb/products/rtma"> Real-time Mesoscale Analysis (RTMA)</a>. Forecasted risk uses data from the',
              '<a href="https://www.weather.gov/mdl/ndfd_home"> National Digital Forecast Database (NDFD)</a>.',
              '</p>',
              '<h3>References</h3>',
              '<p>Fidanza, M.A. P.H. Dernoeden, and A. P. Grybauskas, 1996:',
              '<i>Development and field validation of a brown patch warning model for perennial ryegrass turf.</i>',
              'Phytopathology 86, 385-390. Plant Disease, 67: 1126-1129',
              '</p>'
             ].join(' '),

      dandelion:['<h3>About Dandelion Control Recommendations</h3>',
                 '<p>Dandelion Control Recommendations are based on accumulated Growing Degree Days (GDD).',
                 '</p>',
                 '<p>For 2,4-D + 2,4-DP Amine, <span class="early">Early</span> indicates that application on Kentucky bluegrass (Poa pratensis L.)',
                 'controls less that 60% of the dandelions present. This occurs with fewer than 150 accumulated base-50°F GDD.',
                 '<span class="favorable">Favorable</span> control (> 80%) is indicated when GDD accumulation exceeds 180. Otherwise <span class="marginal">Marginal</span> control',
                 'can be expected. These thresholds are based on (reference).',
                 '</p>',
                 '<p>For 2,4-D + 2,4-DP Ester, <span class="early">Early</span> indicates that application on Kentucky bluegrass (Poa pratensis L.)',
                 'controls less that 60% of the dandelions present. This occurs with fewer than 130 accumulated base-50°F GDD.',
                 '<span class="favorable">Favorable</span> control (>80%) is indicated when GDD accumulation exceeds 145. Otherwise <span class="marginal">Marginal</span> control',
                 'can be expected. These thresholds are based on (reference).',
                 '</p>',
                 '<p>The weather data used to compute the Growing Degree Days (GDD) upon which these recomendations',
                 'are based is from the National Weather Service’s <a href="http://www.nco.ncep.noaa.gov/pmb/products/rtma">Real-time Mesoscale Analysis (RTMA)</a>.',
                 'Forecasted recommendations use data from the <a href="https://www.weather.gov/mdl/ndfd_home">National Digital Forecast Database (NDFD)</a>.',
                 '</p>',
                ].join(' '),

      dspot:['<h3>About Dollarspot Disease Risk</h3>',
             '<p>The Dollarspot risk index is based on the models of <i>Mills and Rothwell</i>',
             'and <i>Hall, R.</i> (see references below) with slight modifications for compatibility',
             'with available gridded weather observations. The model combines relative humidity (RH)',
             'leaf wetness (Lw), air temperature (T) and number of consecutive days with rainfall into',
             'a single index (Id) that is used to estimate the risk of an outbreak. The equation',
             'describing the index is :',
             '</p>',
             '<p>&nbsp;&nbsp;&nbsp;&nbsp;<i>Ia = Drh + Dlw + Drain</i>',
             '</p>',
             '<p>Each variable in the equation is originally set to zero. Drh is set to 1 when 3 or more hours',
             'during the previous seven days had both an RH of greater than 90% and a temperature greater',
             'than 25°C (77°F). Dlw is set to 1 if the average daily temperature exceeds 15°C (59°F) and',
             'the average number of hours per day that leaf wetness was present during the previous 3 days',
             'exceeds 8. Any hourly weather observation that reports either rainfall or a dew point that is',
             'less than three degrees (°C) lower than the air temperature indicates the occurrence leaf',
             'wetness during that hour and the next hour. Drain is assigned a value of 1 under two conditions:',
             '&nbsp;&nbsp;&nbsp;a) when three or more consecutive days received rainfall and the average temperature',
             '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;on these days exceeded 15°C (59°F)',
             '&nbsp;&nbsp;&nbsp;b) when two or more consecutive days received rainfall and the average temperature',
             '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;on these days exceeded 20°C (68°F).',
             '</p>',
             '<p>On a daily basis, <span class="high">high risk</span> is indicated when the average of the index over previous 3 days',
             'exceeds 0.7. <span class="moderate">Moderate risk</span> corresponds to 3-day average index values between 0.4 and 0.7.',
             '<span class="no_risk">Low risk</span> is assumed for 3-day average index values of 0.4 or less. In general higher index values',
             'occur with warmer and wetter conditons.',
             '</p>',
             '<p>The weekly index values reflect the longer-term persistence of Dollarspot risk. They are simply',
             'a 7-day average of the daily index values. High, Moderate and low risk are based on the same index',
             'thresholds, but using the 7-day average rather than daily values. In general, <span class="high">high weekly risk</span>',
             'indicates consistent (4 or more days) of moderate to high daily risk, <span class="moderate">moderate weekly risk</span> indicates',
             '2 or 3 days of moderate to high daily risk and <span class="no_risk">low weekly risk</span> indicates 2 or fewer days with',
             'moderate risk.',
             '</p>',
             '<p>The weather data used to compute the Dollarspot index is from the National Weather',
             'Service’s <a href="http://www.nco.ncep.noaa.gov/pmb/products/rtma"> Real-time Mesoscale Analysis (RTMA)</a>. Forecasted risk uses data from the',
             '<a href="https://www.weather.gov/mdl/ndfd_home"> National Digital Forecast Database (NDFD)</a>.',
             '</p>',
             '<h3>References</h3>',
             '<p>Mills, S.G. and Rothwell, J.D. 1982: <i>Predicting diseases - the hygrothermograph.</i>',
             'Greenmaster, 18(4), 14-15<p>',
             '<p>Hall, R. 1984:',
             '<i>Relationship between weather factors and dollar spot of creeping bentgrass.</i>',
             'Can. J. Plant Sci. 64: 167-174',
             '</p>',
            ].join(' '),

      hstress:['<h3>About the Heat Stress Index</h3>',
               '<p>The Heat Stress Index is simply the number of nighttime (8 pm to 7 am) hours in',
               'which the temperature exceeds 69°F and the sum of temperature and relative humidity',
               'exceeds 150.',
               '</p>',
               '<p>On a daily basis, <span class="high">high risk</span> is indicated for a heat stress index of 5 or more hours.',
               '<span class="moderate">Moderate risk</span> is associated with a heat stress index of 2-4 hours. <span class="no_risk">Low risk</span> is assumed',
               'otherwise.',
               '</p>',
               '<p>The weather data used to compute the Pythium Blight index is from the National Weather',
               'Service’s <a href="http://www.nco.ncep.noaa.gov/pmb/products/rtma"> Real-time Mesoscale Analysis (RTMA)</a>. Forecasted risk uses data from the',
               '<a href="https://www.weather.gov/mdl/ndfd_home"> National Digital Forecast Database (NDFD)</a>.',
               '</p>',
              ].join(' '),

      pblight:['<h3>About Pythium Blight Disease Risk</h3>',
             '<p>The Pythium Blight risk index is based on the model of <i>Nutter et al. (1983)</i>',
             '(see references below) with slight modifications for compatibility with available',
             'gridded weather observations. The model combines relative humidity and air temperature',
             'into a single index (Ipb) that is used to estimate the risk of an outbreak. The',
             'equation describing the index is :',
             '</p>',
             '<p>&nbsp;&nbsp;&nbsp;&nbsp;<i>Ipb = (T<sub>max</sub> - 86) + (T<sub>min</sub> - 68) + 0.5(RH<sub>89</sub> - 6)</i>',
             '</p>',
             '<p>T<sub>max</sub> and T<sub>min</sub> are daily maximum and minimum temperature, respectively and',
             'RH<sub>89</sub> is the number of hours in the day that RH exceeds 89%.',
             '</p>',
             '<p>On a daily basis, <span class="high">high risk</span> is indicated when the average of the index over previous 3 days',
             'exceeds 3.6. <span class="moderate">Moderate risk</span> corresponds to 3-day average index values between 0.4 and 3.6.',
             '<span class="no_risk">Low risk</span> is assumed for 3-day average index values of  0.4 or less. In general, higher index',
             'values occur with higher temperatures and relative humidity.',
             '</p>',
             '<p>The weekly index values reflect the longer-term persistence of Pytium Blight risk.',
             'They are simply a 7-day average of the daily index values. High, Moderate and low risk are',
             'based on the same index thresholds, but using 7-day averages rather than the daily values.',
             'In general, <span class="high">high weekly risk</span> indicates consistent (4 or more days) of moderate to high daily',
             'risk, <span class="moderate">moderate weekly risk</span> indicates 2 or 3 days of moderate to high daily risk and',
             '<span class="no_risk">low weekly risk</span> indicates 2 or fewer days with moderate risk.',
             '</p>',
             '<p>The weather data used to compute the Pythium Blight index is from the National Weather',
             'Service’s <a href="http://www.nco.ncep.noaa.gov/pmb/products/rtma"> Real-time Mesoscale Analysis (RTMA)</a>. Forecasted risk uses data from the',
             '<a href="https://www.weather.gov/mdl/ndfd_home"> National Digital Forecast Database (NDFD)</a>.',
             '</p>',
             '<h3>References</h3>',
             '<p>Nutter, F.W., H. Cole, and R.D. Schein, 1983:',
             '<i>Disease forecasting systems for warm weather pythium blight of turfgrass.</i>',
             'Plant Dis. 67:1126',
             '</p>'
            ].join(' '),

/*
      <span class="early">Early</span>
      <span class="favorable">Favorable</span>
      <span class="marginal">Marginal</span>
      <span class="late">Late</span>
*/

      seedhead:['<h3>About Seedhead Control Recommendations</h3>',
                '<p>Base 32°F growing degree day (GDD) accumulation is an experimental measure for predicting ideal',
                'annual bluegrass seedhead development and potential treatment with plant growth regulators.',
                'Preliminary data suggests that the Ideal application is from 200 to 300 GDD for Proxy and',
                '350 to 450 GDD for Embark. Control using Proxy is Marginal for GDD accumulations between 300 and 500.',
                'Marginal control using Embark can be obtained between 450 and 650 GDD. Otherwise the current state',
                'of seedhead development is either Too Early or Too Late for effective control.',
                '</p>',
                '<p>The weather data used to compute the Growing Degree Days (GDD) upon which these recomendations',
                'are based is from the National Weather Service’s <a href="http://www.nco.ncep.noaa.gov/pmb/products/rtma">Real-time Mesoscale Analysis (RTMA)</a>.',
                'Forecasted recommendations use data from the <a href="https://www.weather.gov/mdl/ndfd_home">National Digital Forecast Database (NDFD)</a>.',
                '</p>',
               ].join(' '),

      gdd32:{
        forecast:['<h3>About This Map</h3>',
            '<p>This map shows the forecast for base 32°F GDD accumulation over',
            'the next week. The forecast is based on guidance from the National',
            'Weather Service 7-day temperature forecast.',
            '</p>',
            '<p>Growing degree days (GDD) are a means by which turf and weed',
            'development can be monitored. Base 32°F GDD accumulation is an',
            'experimental measure for predicting ideal annual bluegrass seedhead',
            'development and potential assessment with plant growth regulators.',
            'Preliminary data suggests that the ideal application time might be',
            'from 400 to 600 GDD for Proxy and 500 to 650 GDD for Embark.',
            '</p>'
           ].join(' '),
        last7days:['<h3>About This Map</h3>',
            '<p>This map shows base 32°F GDD accumulation over the last 7 days.',
            '</p>',
            '<p>Growing degree days (GDD) are a means by which turf and weed',
            'development can be monitored. Base 32°F GDD accumulation is an',
            'experimental measure for predicting ideal annual bluegrass seedhead',
            'development and potential assessment with plant growth regulators.',
            'Preliminary data suggests that the ideal application time might be',
            'from 400 to 600 GDD for Proxy and 500 to 650 GDD for Embark.',
            '</p>'
            ].join(' '),
      },

      gdd50:{
        diffdays:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>In terms of days, the GDD comparisons are able to',
              'answer the question, "When during the previous growing season did',
              'the current 50°F GDD accumulation occur ?" A mapped value of -7',
              'indicates that the current season is 7 days behind the previous',
              'year\'s accumulation. If 58 GDD were accumulated on April 7, 2017,',
              'a value of -7 would indicate that 58 GDD had already been accumulated',
              'on April 1, 2016.',
              '</p>'
             ].join(' '),
        diffgdd:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>In terms of GDD, the comparisons are able to',
              'answer the question, "How different is the GDD accumulation in the',
              'current growing season from the same day in the previous season ?"',
              'A mapped value of -25 indicates that the GDD accummulation in the',
              'current year is 25 GGD less than was accumulated in the previous',
              'year. For example, if 48 GDD have accumulated by April 7 this',
              'year, a value of -25 would indicate that 73 GDD had already been',
              'accumulated by April 7 of the previous year.',
              '</p>'
             ].join(' '),
        forecast:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>This map shows the forecast for base 50°F GDD',
              'accumulation over the next week. The forecast is based on guidance from',
              'the National Weather Service 7-day temperature forecast.',
              '</p>'
             ].join(' '),
        last7days:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>This map shows the number of base 50°F growing degree',
              'days (GDD) that have accumulated over the last 7 days.',
              '</p>'
             ].join(' '),
        normdiffdays:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>In terms of days, the GDD comparisons are able to',
              'answer the question, "When during an average growing season did',
              'the current 50°F GDD accumulation occur ?" A mapped value of -7',
              'indicates that the current season is 7 days behind the average',
              'season accumulation.</p><p>For example, if 58 GDD have accumulated',
              'by April 7 of this year, then a value of -7 would indicate that',
              'historically, an average of 58 GDD have already accumulated by',
              'April 1.',
              '</p>'
             ].join(' '),
        normdiffgdd:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>In terms of GDD, the comparisons are able to',
              'answer the question, "When during an average growing season did',
              'the current 50°F GDD accumulation occur ?" A mapped value of 22',
              'indicates that GDD accumulation in the current season is greater',
              'the historical average accumulation.</p><p>For example, if 78 GDD',
              'have been accumulated by April 7 of the current year, a value of',
              '22 would indicate that, historically, an average of only 53 GDD',
              'have accumulated by April 7.',
              '</p>'
             ].join(' '),
        season:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>This map shows the total accumulation of base 50°F',
              'GDD from March 15 until the current day.',
              '</p>'
             ].join(' '),
      },

      irrigate:{
        evapot:['<h3>About This Map</h3>',
              '<p>The Penman Monteith equation is used to calculate the total',
              'potential evapotranspiration (inches) over the last 7 days at',
              'approximately 200 sites used to generate this map.',
              '</p>'
             ].join(' '),
        moisdef:['<h3>About This Map</h3>',
              '<p>Moisture deficit is the difference between rainfall and',
              'evapotranspiration.</p><p>This map depicts total mositure deficet',
              'for the past week. Negative values indicate that evapotranspiration',
              'exceeded precipitation. Positive values indicate the precipitation',
              'exceeded evapotranspiration.</p><p>Data on this map is useful for',
              'assessing irrigation requirements.',
              '</p>'
             ].join(' '),
        moisdefcst:['<h3>About This Map</h3>',
              '<p>Moisture deficit is the difference between rainfall and',
              'evapotranspiration.</p><p>This map displays the forecast moisture deficit',
              'for the next 3-days. Negative values indicate that evapotranspiration',
              'will exceeded precipitation over the next 3 days. Positive values',
              'indicate the precipitation will exceed evapotranspiration.</p><p>Data on',
              'this map is useful for assessing irrigation requirements.',
              '</p>'
             ].join(' '),
        rainfall:['<h3>About This Map</h3>',
              '<p>Approximately 700 rain gauge sites are used to map the total',
              'rainfall (inches) observed over the last 7 days.',
              '</p>'
             ].join(' '),
      },
      temperature:{
        departure:['<h3>About This Map</h3>',
              '<p>The average of the temperatures over past 30 years on any particular',
              'day is commonly called the "normal". As depicted here, "departure" is',
              'the difference between the average temperature (°F) over the last 7 days',
              'and average of the normal temperatures for the same 7 days.</p>',
              '<p>Negative values indicate areas where temperatures are cooler than',
              'normal. Positive values indicate areas where temperatures are warmer',
              'than normal.',
              '</p>'
             ].join(' '),
        frost:['<h3>About This Map</h3>',
               '<p>This map shows the lowest temperature that has occurred',
               'from July 1st to present, visually depicting which areas',
               'have had below-freezing temperatures.',
               '</p>'
             ].join(' '),
        soil2in:['<h3>About This Map</h3>',
              '<p>Temperature (°F) of the soil 2" below the surface.</p>'
             ].join(' '),
      },
    }  
  }

  description = function(text_key) {
    console.log('TurfTextStore dcescription('+text_key+')')
    if (text_key.includes('.')) {
      let keys = text_key.split('.');
      return this.descriptions[keys[0]][keys[1]];
    } else {
      return this.descriptions[text_key];
    }
  }

}

