
/*
Mills, S.G. and Rothwell, J.D. 1982: Predicting diseases - the hygrothermograph. Greenmaster, 18(4), 14-15.
*/


export default class TurfTextStore {
  app;
  constructor(app) {
    this.app = app;

    this.descriptions = {

      anthrac:['<h3>About Anthracnose Disease Risk</h3>',
               '<p>On a daily basis,',
               '<span class="high">High risk</span> indicates ...', 
               '<span class="moderate">Moderate risk</span> indicates ...',
               '<span class="no_risk">Low risk</span> indicates .... ',
               '</p>',
               '<p>On a weekly basis',
               '<span class="high">High risk</span> indicates consistent (typically',
               'more than 4 days) of moderate to high daily risk.',
               '<span class="moderate">Moderate risk</span> indicates 2 or 3 days',
               'of moderate to high daily risk.',
               '<span class="no_risk">Low risk</span> indicates 2 or fewer days with',
               'moderate risk.',
               '</p>',
               '<p>The Anthracnose risk index is based on the model of <i>Danneberger',
               'et al.</i> (see references below) with slight modifications for compatibility with NWS',
               'gridded weather data. This model uses a combination of leaf wetness and air temperature',
               'to estimate the risk of an outbreak.',
               '</p>',
               '<p>All resulta are based on guidance from National Weather Service databases.',
               'Observations are based on data from the Real-time Mesoscale Analysis (RTMA) product.',
               'Forecasts are based on data from the National Digital Forecast Database (NDFD).',
               '</p>',
               '<h3>References</h3>',
               '<p>Danneberger, T.K., J.M. Vargas Jr., and A.L. Jones, 1984:',
               '<i>A model for weather-based forecasting of anthracnose on annual bluegrass.</i>',
               'Phytopathology, 74, 448-451</p>'
              ].join(' '),

      bpatch:['<h3>About Brown Patch Disease Risk</h3>',
              '<p>On a daily basis,',
              '<span class="high">High risk</span> indicates ...',
              '<span class="moderate">Moderate risk</span> indicates ...',
              '<span class="no_risk">Low risk</span> indicates ...',
              '</p>',
              '<p>On a weekly basis',
              '<span class="high">High risk</span> indicates 4 or more days with conditions conducive to disease infection.',
              '<span class="moderate">Moderate risk</span> indicates between 2 and 3 days per week of exposure.',
              '<span class="no_risk">Low risk</span> indicates fewer than 2 days of exposure.',
              '</p>',
              '<p>The Brown Patch risk index is based on the model of <i>Fidanza et al.</i> (see references below)',
              'with slight modifications for compatibility with NWS gridded weather data.',
              'This model uses a combination of relative humidity, leaf wetness and',
              'minimum daily air temperature to estimate the risk of an outbreak.',
              '</p>',
              '<p>All resulta are based on guidance from National Weather Service databases.',
              'Observations are based on data from the Real-time Mesoscale Analysis (RTMA) product.',
              'Forecasts are based on data from the National Digital Forecast Database (NDFD).',
              '</p>',
              '<h3>References</h3>',
              '<p>Fidanza, M.A. P.H. Dernoeden, and A. P. Grybauskas, 1996:',
              '<i>Development and field validation of a brown patch warning model for perennial ryegrass turf.</i>',
              'Phytopathology 86, 385-390. Plant Disease, 67: 1126-1129<p>'
             ].join(' '),

      dandelion:['<h3>About Dandelion Control Recommendations</h3>',
                 '<p><span class="early">Early</span> indicates application will produce unacceptable results.',
                 '<span class="marginal">Moarginal</span> indicates application will produce marginal results.',
                 '<span class="favorable">Favorable</span> indicates appliction will produce acceptable results.',
                 '</p>',
                 '<p>Research has shown that applications of 2,4-D + 2,4-DP Ester applied to Kentucky bluegrass',
                 '(<i>Poa pratensis L.</i>) controlled less than 60% of the dandelions present when fewer than 130 base 50°F',
                 'degree days had accumulated. Acceptable control (>80%) was achieved when the degree day accumulation',
                 'exceeded 145 GDD.',
                 '</p>',
                 '<p>When applying 2,4-D + 2,4-DP Amine, unacceptable control occurred with accumulation of less than',
                 '150 base 50°F degree days, while acceptable control was indicated at degree day accumulations above 180 GDD.',
                 '</p>',
                ].join(' '),

      dspot:['<h3>About Dollarspot Disease Risk</h3>',
             '<p>On a daily basis',
             '<span class="high">High risk</span> indicates ...', 
             '<span class="moderate">Moderate risk</span> indicates ...',
             '<span class="no_risk">Low risk</span> indicates ...',
             '</p>',
             '<p>On a weekly basis,',
             '<span class="high">High risk</span> indicates 4 or more days with conditions conducive to disease infection',
             '<span class="moderate">Moderate risk</span> indicates 2 or 3 days or exposure',
             '<span class="no_risk">Low risk</span> indicates fewer than 2 days of exposure.',
             '</p>',
             '<p>The Dollarspot risk index is based on the models of <i>Mills and Rothwell</i>',
             'and <i>Hall, R.</i> (see references below)',
             'with slight modifications for compatibility with NWS gridded weather data.',
             'This model uses a combination of relative humidity, air temperature, leaf wetness hours',
             'and the number of consecutive days with rain to estimate risk of an outbreak.',
             '</p>',
             '<p>All resulta are based on guidance from National Weather Service databases.',
             'Observations are based on data from the Real-time Mesoscale Analysis (RTMA) product.',
             'Forecasts are based on data from the National Digital Forecast Database (NDFD).',
             '</p>',
             '<h3>References</h3>',
             '<p>Mills, S.G. and Rothwell, J.D. 1982: <i>Predicting diseases - the hygrothermograph.</i>',
             'Greenmaster, 18(4), 14-15<p>',
             '<p>Hall, R. 1984:',
             '<i>Relationship between weather factors and dollar spot of creeping bentgrass.</i>',
             'Can. J. Plant Sci. 64: 167-174',
             '</p>',
            ].join(' '),

      hstress:['<h3>About the Heat Stress Index</h3>',
               '</p>',
               '<p>On a daily basis,',
               '<span class="high">High risk</span> indicates 8 or more heat stress hours.',
               '<span class="moderate">Moderate risk</span> indicates 4 to 7 heat stress hours.',
               '<span class="no_risk">Low risk</span> indicates less than 4 heat stress hours.',
               '</p>',
               '<p>On a weekly basis,',
               '<span class="high">High risk</span> indicates more than 4 days with moderate risk.',
               '<span class="moderate">Moderate risk</span> indicates 3 or 4 days with moderate risk.',
               '<span class="no_risk">low risk</span> indicates for less than 3 days with moderate risk.',
               '</p>',
               '<p>Heat stress occurs when the sum of the air temperature (°F) and relative',
               'humidity (%) exceeds 150 during any nighttime hour (8:00 pm through 8:00 am).',
               '<p>All resulta are based on guidance from National Weather Service databases.',
               'Observations are based on data from the Real-time Mesoscale Analysis (RTMA) product.',
               'Forecasts are based on data from the National Digital Forecast Database (NDFD).',
               '</p>',
              ].join(' '),

      pblight:['<h3>About Pythium Blight Disease Risk</h3>',
             '<p>On a daily basis,',
             '<span class="high">High risk</span> indicates ...', 
             '<span class="moderate">Moderate risk</span> indicates ...',
             '<span class="no_risk">Low risk</span> indicates ...',
             '</p>',
             '<p>On a weekly basis',
             '<span class="high">High risk</span> indicates 4 or more days with conditions conducive to disease infection',
             '<span class="moderate">Moderate risk</span> indicates 2 or 3 days or exposure',
             '<span class="no_risk">Low risk</span> indicates fewer than 2 days of exposure.',
             '</p>',
             '</p>',
             '<p>The Pythium Blight risk index is based on the model of Nutter et al. (see references below)',
             'with slight modifications for compatibility with NWS gridded weather data.',
             'This model uses a combination of relative humidity and air temperature to estimate the risk of an outbreak.',
             '</p>',
             '<p>All resulta are based on guidance from National Weather Service databases.',
             'Observations are based on data from the Real-time Mesoscale Analysis (RTMA) product.',
             'Forecasts are based on data from the National Digital Forecast Database (NDFD).',
             '</p>',
             '<h3>References</h3>',
             '<p>Nutter, F.W., H. Cole, and R.D. Schein, 1983:',
             '<i>Disease forecasting systems for warm weather pythium blight of turfgrass.</i>',
             'Plant Dis. 67:1126<p>'
            ].join(' '),

      seedhead:['<h3>About Seedhead Control Recommendations</h3>',
                '<p><span class="early">Early</span> indicates application will produce unacceptable results.',
                '<span class="marginal">Moarginal</span> indicates application will produce marginal results.',
                '<span class="favorable">Favorable</span> indicates appliction will produce optimal results.',
                '</p>',
                '<p>Base 32°F growing degree day accumulation is an experimental measure for predicting ideal',
                'annual bluegrass seedhead development and potential assessment with plant growth regulators.',
                'Preliminary data suggests that the ideal application time might be from 200 to 300 GDD for Proxy',
                'and 350 to 450 GDD for Embark.',
                '</p>',
               ].join(' '),

      gdd32:{
        forecast:['<h3>About This Map</h3>',
            '<p>This map shows the forecast for base 32°F GDD accumulation over',
            'the next week. The forecast is based on guidance from the National',
            'Weather Service 7-day temperature forecast.</p>',
            '<p>Growing degree days (GDD) are a means by which turf and weed',
            'development can be monitored. Base 32°F GDD accumulation is an',
            'experimental measure for predicting ideal annual bluegrass seedhead',
            'development and potential assessment with plant growth regulators.',
            'Preliminary data suggests that the ideal application time might be',
            'from 400 to 600 GDD for Proxy and 500 to 650 GDD for Embark.</p>'
           ].join(' '),
        last7days:['<h3>About This Map</h3>',
            '<p>This map shows base 32°F GDD accumulation over the last 7 days.</p>',
            '<p>Growing degree days (GDD) are a means by which turf and weed',
            'development can be monitored. Base 32°F GDD accumulation is an',
            'experimental measure for predicting ideal annual bluegrass seedhead',
            'development and potential assessment with plant growth regulators.',
            'Preliminary data suggests that the ideal application time might be',
            'from 400 to 600 GDD for Proxy and 500 to 650 GDD for Embark.</p>'
            ].join(' '),
      },

      gdd50:{
        diffdays:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>In terms of days, the GDD comparisons are able to',
              'answer the question, "When during the previous growing season did',
              'the current 50°F GDD accumulation occur ?" A mapped value of -7',
              'indicates that the current season is 7 days behind the previous',
              'year\'s accumulation. If 58 GDD were accumulated on April 7, 2017,',
              'a value of -7 would indicate that 58 GDD had already been accumulated',
              'on April 1, 2016.</p>'
             ].join(' '),
        diffgdd:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>In terms of GDD, the comparisons are able to',
              'answer the question, "How different is the GDD accumulation in the',
              'current growing season from the same day in the previous season ?"',
              'A mapped value of -25 indicates that the GDD accummulation in the',
              'current year is 25 GGD less than was accumulated in the previous',
              'year. For example, if 48 GDD have accumulated by April 7 this',
              'year, a value of -25 would indicate that 73 GDD had already been',
              'accumulated by April 7 of the previous year.</p>'
             ].join(' '),
        forecast:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>This map shows the forecast for base 50°F GDD',
              'accumulation over the next week. The forecast is based on guidance from',
              'the National Weather Service 7-day temperature forecast.</p>'
             ].join(' '),
        last7days:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>This map shows the number of base 50°F growing degree',
              'days (GDD) that have accumulated over the last 7 days.</p>'
             ].join(' '),
        normdiffdays:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>In terms of days, the GDD comparisons are able to',
              'answer the question, "When during an average growing season did',
              'the current 50°F GDD accumulation occur ?" A mapped value of -7',
              'indicates that the current season is 7 days behind the average',
              'season accumulation.</p><p>For example, if 58 GDD have accumulated',
              'by April 7 of this year, then a value of -7 would indicate that',
              'historically, an average of 58 GDD have already accumulated by',
              'April 1.</p>'
             ].join(' '),
        normdiffgdd:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>In terms of GDD, the comparisons are able to',
              'answer the question, "When during an average growing season did',
              'the current 50°F GDD accumulation occur ?" A mapped value of 22',
              'indicates that GDD accumulation in the current season is greater',
              'the historical average accumulation.</p><p>For example, if 78 GDD',
              'have been accumulated by April 7 of the current year, a value of',
              '22 would indicate that, historically, an average of only 53 GDD',
              'have accumulated by April 7.</p>'
             ].join(' '),
        season:['<h3>About This Map</h3>',
              '<p>Degree days are a means by which turf and weed development can be',
              'monitored.</p><p>This map shows the total accumulation of base 50°F',
              'GDD from March 15 until the current day.</p>'
             ].join(' '),
      },

      irrigate:{
        evapot:['<h3>About This Map</h3>',
              '<p>The Penman Monteith equation is used to calculate the total',
              'potential evapotranspiration (inches) over the last 7 days at',
              'approximately 200 sites used to generate this map.</p>'
             ].join(' '),
        moisdef:['<h3>About This Map</h3>',
              '<p>Moisture deficit is the difference between rainfall and',
              'evapotranspiration.</p><p>This map depicts total mositure deficet',
              'for the past week. Negative values indicate that evapotranspiration',
              'exceeded precipitation. Positive values indicate the precipitation',
              'exceeded evapotranspiration.</p><p>Data on this map is useful for',
              'assessing irrigation requirements.</p>'
             ].join(' '),
        moisdefcst:['<h3>About This Map</h3>',
              '<p>Moisture deficit is the difference between rainfall and',
              'evapotranspiration.</p><p>This map displays the forecast moisture deficit',
              'for the next 3-days. Negative values indicate that evapotranspiration',
              'will exceeded precipitation over the next 3 days. Positive values',
              'indicate the precipitation will exceed evapotranspiration.</p><p>Data on',
              'this map is useful for assessing irrigation requirements.</p>'
             ].join(' '),
        rainfall:['<h3>About This Map</h3>',
              '<p>Approximately 700 rain gauge sites are used to map the total',
              'rainfall (inches) observed over the last 7 days.</p>'
             ].join(' '),
      },
      temperature:{
        departure:['<h3>About This Map</h3>',
              '<p>The average of the temperatures over past 30 years on any particular',
              'day is commonly called the "normal". As depicted here, "departure" is',
              'the difference between the average temperature (°F) over the last 7 days',
              'and average of the normal temperatures for the same 7 days.</p>',
              '<p>Negative values indicate areas where temperatures are cooler than',
              'normal. Positive values indicate areas where temperatures are warmer',
              'than normal.</p>',
             ].join(' '),
        frost:['<h3>About This Map</h3>',
               '<p>This map shows the lowest temperature that has occurred',
               'from July 1st to present, visually depicting which areas',
               'have had below-freezing temperatures.</p>'
             ].join(' '),
        soil2in:['<h3>About This Map</h3>',
              '<p>Temperature (°F) of the soil 2" below the surface.</p>'
             ].join(' '),
      },
    }  
  }

  description = function(text_key) {
    console.log('TurfTextStore dcescription('+text_key+')')
    if (text_key.includes('.')) {
      let keys = text_key.split('.');
      return this.descriptions[keys[0]][keys[1]];
    } else {
      return this.descriptions[text_key];
    }
  }

}

